### ISSUE TITLE
Another path to localstorage

### ISSUE THREAD

**Issue by merryejik** [wootwoot1234/react-native-webkit-localstorage-reader#4]
NSString *databasePath = [libraryDir
                              stringByAppendingPathComponent:@"WebKit/WebsiteData/LocalStorage/"];

Some more information about paths in this code: https://github.com/MaKleSoft/cordova-plugin-migrate-localstorage/blob/master/src/ios/MigrateLocalStorage.m

**Comment by wootwoot1234** [comment]
Ok, thanks. What am I looking for?

**Comment by merryejik** [comment]
I made pull request.
UIWebView had localstorage at WebKit/LocalStorage. But from iOS8 we should use WKWebView. Localstorage is there at "WebKit/WebsiteData/LocalStorage".

**Comment by wootwoot1234** [comment]
I just merged https://github.com/wootwoot1234/react-native-webkit-localstorage-reader/pull/6 and published your changes to npm.  Thanks again!

**Comment by merryejik** [comment]
And thanks you too, that I don't need to do all this staff for myself :)
